import type { SessionDetail } from "./types"

export const mockSessions: SessionDetail[] = [
  {
    id: "abc-123",
    week: "8",
    status: "completed",
    qualityScore: 94,
    executionTime: "3.2s",
    date: "Nov 19",
    fullTimestamp: "Nov 19, 2025 3:42 PM",
    user: "demo_user",
    cacheHitRate: 78,
    cost: "$0.04",
    agents: [
      {
        name: "Revenue",
        status: "completed",
        confidence: 0.92,
        executionTime: "1.2s",
        cacheStatus: "HIT",
      },
      {
        name: "Product",
        status: "completed",
        confidence: 0.88,
        executionTime: "1.5s",
        cacheStatus: "MISS",
      },
      {
        name: "Support",
        status: "completed",
        confidence: 0.85,
        executionTime: "1.1s",
        cacheStatus: "HIT",
      },
      {
        name: "Synthesizer",
        status: "completed",
        confidence: 0.91,
        executionTime: "2.1s",
        cacheStatus: "MISS",
      },
      {
        name: "Evaluation",
        status: "completed",
        confidence: 0.94,
        executionTime: "0.5s",
        cacheStatus: "N/A",
      },
    ],
    governance: {
      passed: 5,
      violations: 0,
      escalations: 0,
    },
    costBreakdown: {
      geminiCost: "$0.04",
      inputTokens: 2150,
      outputTokens: 1850,
    },
  },
  {
    id: "def-456",
    week: "7",
    status: "completed",
    qualityScore: 91,
    executionTime: "2.8s",
    date: "Nov 12",
    fullTimestamp: "Nov 12, 2025 2:15 PM",
    user: "admin_user",
    cacheHitRate: 82,
    cost: "$0.03",
    agents: [
      {
        name: "Revenue",
        status: "completed",
        confidence: 0.89,
        executionTime: "1.1s",
        cacheStatus: "HIT",
      },
      {
        name: "Product",
        status: "completed",
        confidence: 0.9,
        executionTime: "1.4s",
        cacheStatus: "HIT",
      },
    ],
    governance: {
      passed: 5,
      violations: 0,
      escalations: 0,
    },
    costBreakdown: {
      geminiCost: "$0.03",
      inputTokens: 1800,
      outputTokens: 1600,
    },
  },
  {
    id: "ghi-789",
    week: "6",
    status: "partial",
    qualityScore: 78,
    executionTime: "5.1s",
    date: "Nov 5",
    fullTimestamp: "Nov 5, 2025 10:30 AM",
    user: "demo_user",
    cacheHitRate: 45,
    cost: "$0.06",
    agents: [
      {
        name: "Revenue",
        status: "completed",
        confidence: 0.85,
        executionTime: "1.5s",
        cacheStatus: "MISS",
      },
      {
        name: "Support",
        status: "error",
        confidence: 0,
        executionTime: "3.0s",
        cacheStatus: "MISS",
      },
    ],
    governance: {
      passed: 3,
      violations: 1,
      escalations: 1,
    },
    costBreakdown: {
      geminiCost: "$0.06",
      inputTokens: 2500,
      outputTokens: 1200,
    },
  },
  {
    id: "jkl-012",
    week: "8",
    status: "failed",
    executionTime: "-",
    date: "Nov 19",
    fullTimestamp: "Nov 19, 2025 4:00 PM",
    user: "system_job",
    cacheHitRate: 0,
    cost: "$0.00",
    agents: [],
    governance: {
      passed: 0,
      violations: 0,
      escalations: 0,
    },
    costBreakdown: {
      geminiCost: "$0.00",
      inputTokens: 0,
      outputTokens: 0,
    },
  },
]
